### ISSUE TITLE
Redirected output has two line breaks between each line on Windows

### ISSUE THREAD

**Issue by benhoyt** [eliben/pss#10]
Because the input files are opened in binary mode and stdout is opened as text, on Windows when redirecting the output to a file you end up with CR CR LF line breaks, which is incorrect, and most editors show as two line breaks (extra blank line in between every line).

The "proper" fix would be to open the file in text mode, but as you're doing binary stuff on it too, it's easiest just to replace CR LF with LF before outputting (which the text-opened stdout will convert back to CR LF).

Fixed in [this commit](https://github.com/benhoyt/pss/commit/0b8788462be8e871f0125decfcc71c7884b36a20)

**Comment by eliben** [comment]
Here too, interested in pushing this through?

[just going through old issues]

**Comment by benhoyt** [comment]
Hmmm, this is not an issue anymore on the latest master, so I guess something fixed it. I thought it might be the `-U` / `--universal-newlines` option, but it looks like that's off by default, so probably something else. In any case, it's fine now. :-)
