### ISSUE TITLE
A simple optimization

### ISSUE THREAD

**Issue by rphilips** [eliben/pss#20]
Hi,

Two things to consider:

in contentmatcher.py: implement \_pattern\_is\_simple as:

def \_pattern\_is\_simple(self, pattern):
        """ A "simple" pattern that can be matched with str.find and doesn't
            require a regex engine.
        """
        return re.escape(pattern) == pattern

**Comment by eliben** [comment]
Closing for lack of interest. Feel free to reopen or create a new issue if this is still relevant
