### ISSUE TITLE
Enhancement suggestion - provide file list file as [files] source

### ISSUE THREAD

**Issue by assaf758** [eliben/pss#35]
Usually I have a file containing all source files of the project (to be used by cscope).
It could be useful if pss can be instructed to use this file as the search space:
For example:
pss --cc --file-list 'file-list.txt' 'malloc'

**Comment by eliben** [comment]
Can't you just use xargs for that?

**Comment by assaf758** [comment]
xargs is possible - didnt think about this. 
I still see some value in my suggestion as sometime you would want to filter further on path like so. 
pss --cc --file-list 'file-list.txt' 'malloc'  /some/path
I assume this also can also be done by greping the xargs before calling pss, but its less convenient)

**Comment by eliben** [comment]
It has been my policy so far to reject features that try to add "unix command-line tool" functionality inside pss. pss is designed to be a good citizen of the command-line world, interacting with other tools like xargs and grep as needed.

I also encourage folks to create aliases/bash functions to encapsulate common uses wrapping pss with additional "features".
