### ISSUE TITLE
Add support for ack's --type-add / --type-set or similar

### ISSUE THREAD

**Issue by benhoyt** [eliben/pss#4]
Some projects I work on use a bunch of not-very-standard file extensions, such as `.tmpl` for mixed HTML templates. With ack I could use `--type-add html=.tmpl` to include this.

It would be great to have this feature in pss. It doesn't need to be permanent, because I always run pss via a customized script with my own options anyway (essentially an ackrc replacement).

One can *kind of* achieve this behaviour with a combination of `-a` and `-G`, but then it only searches .tmpl files, whereas I want to include them in all my searches by default. Basically `--type-add` would add to `TYPE_MAP`.

Let me know if you'd like a patch for this. I think it'd be pretty straight-forward to add these options and have them adjust TYPE_MAP.

**Comment by eliben** [comment]
Hope your move went well. Still interested in putting the finishing touch here?

**Comment by benhoyt** [comment]
Sorry, this isn't an issue for me anymore and I'm kinda working on other projects now, so I have no real desire to get this into shape now. Sorry!

**Comment by eliben** [comment]
OK, no worries
