### ISSUE TITLE
Enhancement request: Support in-plce replace a-la sed

### ISSUE THREAD

**Issue by adamatan** [eliben/pss#40]
I use `pss` extensively because I feel comfortable with Python's regex format, which I prefer over [the one `sed` uses](https://www.gnu.org/software/sed/manual/html_node/Regular-Expressions.html).

However, `sed` is extremely useful for recursive in-place regex replace.

Do you think it would be a good idea to add search-and-replace features to `pss`, using `re.sub`?

**Comment by eliben** [comment]
Nope, I never planned replacement features for pss because you could always `xargs`-combine it with `sed`. The design goal for pss is to be able to find source files easily without passing too many options to `grep` or `find`.

**Comment by adamatan** [comment]
Thanks.
I'm using `xargs` extensively, but I have to re-write the regex in the `sed` format. Am I missing anything?
Would you be open for a PR that implements the substitution, or would you prefer that I develop it separately?

**Comment by adamatan** [comment]
http://stackoverflow.com/questions/42655786/converting-regular-expression-syntax-from-python-to-posix

**Comment by eliben** [comment]
Feel free to develop it separately.

By the way, if the regexp conversion bothers you, you could use `perl` instead of `sed`
