### ISSUE TITLE
Differences with silver-searcher and rgrep

### ISSUE THREAD

**Issue by DamienCassou** [eliben/pss#46]
What are the differences between pss and [silver-searcher/ag](https://github.com/ggreer/the_silver_searcher) and [ripgrep](https://github.com/BurntSushi/ripgrep)?

**Comment by eliben** [comment]
Here's the comparison with ack that was made a long while ago when pss was starting: https://github.com/eliben/pss/wiki/pss-and-ack

Presumably more ack-like tools popped up recently, but I'm not really keeping close track of these developments
