### ISSUE TITLE
Syntax aware searcher

### ISSUE THREAD

**Issue by techtonik** [eliben/pss#51]
Hi Eli. Does `pss` tool support syntax-aware search that can look inside Python strings only? I need to find a specific string value, but unfortunately it is also a rather common word for my codebase. I could [parse AST](https://pypi.org/project/astdump/) myself, but it is not practical for daily usage.

**Comment by eliben** [comment]
No, there's no syntax-aware search in `pss`

**Comment by techtonik** [comment]
I found my own links and some new for AST based search. For some reason `pss` is among them. I guess the refreshed list to review for this functionality can be brought from https://github.com/search?q=ast+code+search but now I am not sure if it worths the hassle. Query languages are not as intuitive as "search in all strings: import".
