### ISSUE TITLE
Command line parser doesn't support multiple occurrences of --include-pattern or --exclude-pattern

### ISSUE THREAD

**Issue by TobiasPleyer** [eliben/pss#54]
If **--include-pattern** or **--exclude-pattern** are given more than once only the last occurrence is taking effect, all others are effectively ignored.

This is sort of counter intuitive. I expected the following invocation:

`pss --include-pattern=A --include-pattern=B`

to be equivalent to

`pss --include-pattern='(A|B)'`

I know that since _pss_ supports Python's regular expression syntax this seems like a mere question of preference, but there exist use cases where the combination behavior is desired.

**Example**
I use vim (neovim) as my editor of choice. Vim supports the _grepprg_ option, that allows to specify an external program to be used for vim's grep command. I prefer to use _pss_ for this, because I am more familiar with PCRE. In addition it is possible to provide the command with command line options that will always be used. Since I develop Qt applications I am dealing with a lot of auto-generated files of the form **moc_.*cpp**. These files are only cluttering the search results so I want them excluded. The problem is when I provide this exclude pattern as part of the default command invocation it is not possible to use **--exclude-pattern** again.
So I am left with one of two options:

1. Write --exclude-pattern='moc_.*cpp' everytime I search something
2. Accept that my search results are cluttered when I use another exclude pattern in a search

**Comment by eliben** [comment]
As you've identified, the right way to address this would be to use argparse (#55)
