### ISSUE TITLE
by default line number is not colored

### ISSUE THREAD

**Issue by clach04** [eliben/pss#71]
Not sure if this is a deliberate design decision. It's different compared to [ack](https://beyondgrep.com/), [ripgrep](https://github.com/BurntSushi/ripgrep), [silver-searcher](https://geoff.greer.fm/ag/).

    diff --git a/psslib/defaultpssoutputformatter.py b/psslib/defaultpssoutputformatter.py
    index 904a6b8..c1ef337 100644
    --- a/psslib/defaultpssoutputformatter.py
    +++ b/psslib/defaultpssoutputformatter.py
    @@ -46,7 +46,8 @@ class DefaultPssOutputFormatter(OutputFormatter):
             self.style_filename = (decode_colorama_color(filename_color_str) or
                                    colorama.Fore.MAGENTA + colorama.Style.BRIGHT)
             self.style_lineno = (decode_colorama_color(lineno_color_str) or
    -                             colorama.Fore.WHITE)
    +                            colorama.Fore.GREEN + colorama.Back.BLACK)
    +        #                     colorama.Fore.WHITE)

             # colorama.init is doing something strange on Linux, by emitting a color
             # reset sequence when it shouldn't. This causes strange errors when

is ripgrep-like.

**Comment by clach04** [comment]
Thanks for making this available! I was able to install this on a few older machines very easily :) I even saw 0.32 working with Python 2.5 :-)

**Comment by eliben** [comment]
You can use the `--color-line`  option if you like.
